package view;

import  controller.binario.ControllerArquivoBinarioCliente;
import  controller.binario.ControllerArquivoBinarioPedido;
import  controller.binario.ControllerArquivoBinarioProduto;
import  controller.texto.ControllerArquivoTextoCliente;
import  controller.texto.ControllerArquivoTextoPedido;
import  controller.texto.ControllerArquivoTextoProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author henri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ControllerArquivoTextoPedido controllerPedidoText;
    ControllerArquivoTextoCliente controllerClienteText;
    ControllerArquivoTextoProduto controllerProdutoText;

    ControllerArquivoBinarioPedido controllerPedidoBin;
    ControllerArquivoBinarioCliente controllerClienteBin;
    ControllerArquivoBinarioProduto controllerProdutoBin;

    /**
     * Creates new form telaPrincipal
     */
    public TelaPrincipal() {

        initComponents();

        if (jRadioButtonBinario.isSelected()) {
            inicializarBinario();
        } else {

            inicializarTexto();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSelecione = new javax.swing.JMenu();
        jRadioButtonBinario = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonTexto = new javax.swing.JRadioButtonMenuItem();
        jMenuAbrir = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemGerenciarCliente = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenu();
        jMenuItemCadastrarPedido = new javax.swing.JMenuItem();
        jMenuItemGerenciarPedido = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenu();
        jMenuItemCadastrarProduto = new javax.swing.JMenuItem();
        jMenuItemGerenciarProduto = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelTitulo.setText("Sistema para Gerência de Pedidos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabelTitulo)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jMenuSelecione.setText("Selecione");

        buttonGroup1.add(jRadioButtonBinario);
        jRadioButtonBinario.setSelected(true);
        jRadioButtonBinario.setText("Binario");
        jMenuSelecione.add(jRadioButtonBinario);

        buttonGroup1.add(jRadioButtonTexto);
        jRadioButtonTexto.setText("Texto");
        jRadioButtonTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTextoMouseClicked(evt);
            }
        });
        jRadioButtonTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTextoActionPerformed(evt);
            }
        });
        jMenuSelecione.add(jRadioButtonTexto);

        jMenuBar1.add(jMenuSelecione);

        jMenuAbrir.setText("Abrir");

        jMenuCliente.setText("Cliente");

        jMenuItemCadastrarCliente.setText("Novo");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadastrarCliente);

        jMenuItemGerenciarCliente.setText("Gerenciar");
        jMenuItemGerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemGerenciarCliente);

        jMenuAbrir.add(jMenuCliente);

        jMenuPedido.setText("Pedido");

        jMenuItemCadastrarPedido.setText("Novo");
        jMenuItemCadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemCadastrarPedido);

        jMenuItemGerenciarPedido.setText("Gerenciar");
        jMenuItemGerenciarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemGerenciarPedido);

        jMenuAbrir.add(jMenuPedido);

        jMenuProduto.setText("Produto");

        jMenuItemCadastrarProduto.setText("Novo");
        jMenuItemCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuItemCadastrarProduto);

        jMenuItemGerenciarProduto.setText("Gerenciar");
        jMenuItemGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarProdutoActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuItemGerenciarProduto);

        jMenuAbrir.add(jMenuProduto);

        jMenuBar1.add(jMenuAbrir);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Tela Principal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
        // TODO add your handling code here:
        abrirTelaCadastroCliente();
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuItemCadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarPedidoActionPerformed
        // TODO add your handling code here:
        abrirTelaCadastroPedido();
    }//GEN-LAST:event_jMenuItemCadastrarPedidoActionPerformed

    private void jMenuItemCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        abrirTelaCadastroProduto();
    }//GEN-LAST:event_jMenuItemCadastrarProdutoActionPerformed

    private void jMenuItemGerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarClienteActionPerformed
        // TODO add your handling code here:
        abrirTelaGerenciaCliente();
    }//GEN-LAST:event_jMenuItemGerenciarClienteActionPerformed

    private void jMenuItemGerenciarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarPedidoActionPerformed
        // TODO add your handling code here:
        abrirTelaGerenciaPedido();
    }//GEN-LAST:event_jMenuItemGerenciarPedidoActionPerformed

    private void jMenuItemGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarProdutoActionPerformed
        // TODO add your handling code here:
        abrirTelaGerenciaProduto();
    }//GEN-LAST:event_jMenuItemGerenciarProdutoActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jRadioButtonTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTextoMouseClicked
        // TODO add your handling code here:
        inicializarTexto();

    }//GEN-LAST:event_jRadioButtonTextoMouseClicked

    private void jRadioButtonTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTextoActionPerformed
        // TODO add your handling code here:]
        inicializarTexto();
    }//GEN-LAST:event_jRadioButtonTextoActionPerformed
    public void abrirTelaCadastroCliente() {
        TelaCadastroCliente janela = new TelaCadastroCliente();

        janela.controllerText = controllerClienteText;

        if (jRadioButtonBinario.isSelected()) {
            janela.controllerBin = controllerClienteBin;

        } else {
            janela.controllerText = controllerClienteText;

        }
        janela.setVisible(true);

    }

    public void abrirTelaGerenciaCliente() {
        TelaGerenciaCliente janela = new TelaGerenciaCliente();

        if (jRadioButtonBinario.isSelected()) {
            janela.controllerBin = controllerClienteBin;

        } else {
            janela.controllerText = controllerClienteText;

        }
        janela.setVisible(true);

    }

    public void abrirTelaCadastroProduto() {
        TelaCadastroProduto janela = new TelaCadastroProduto();
        if (jRadioButtonBinario.isSelected()) {
            janela.controllerBin = controllerProdutoBin;

        } else {
            janela.controllerText = controllerProdutoText;

        }
        janela.setVisible(true);

    }

    public void abrirTelaGerenciaProduto() {
        TelaGerenciaProduto janela = new TelaGerenciaProduto();
        if (jRadioButtonBinario.isSelected()) {
            janela.controllerBin = controllerProdutoBin;

        } else {
            janela.controllerText = controllerProdutoText;

        }
        janela.setVisible(true);
    }

    public void abrirTelaCadastroPedido() {

        if (       controllerClienteBin.getArquivo() != null
                || controllerProdutoBin.getArquivo() != null
                || controllerProdutoText.getArquivo() != null
                || controllerClienteText.getArquivo() != null) {

            TelaCadastroPedido janela = new TelaCadastroPedido();
            if (jRadioButtonBinario.isSelected()) {
                janela.controllerBin = controllerPedidoBin;
                janela.controllerClienteBin = controllerClienteBin;
                janela.controllerProdutoBin = controllerProdutoBin;
            } else {
                janela.controllerProdutoText = controllerProdutoText;
                janela.controllerClienteText = controllerClienteText;
                janela.controllerText = controllerPedidoText;

            }

            janela.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum arquivo de Cliente ou Produto selecionado",
                    "Alerta", JOptionPane.WARNING_MESSAGE);

        }

    }

    public void abrirTelaGerenciaPedido() {

        TelaGerenciaPedido janela = new TelaGerenciaPedido();
        if (jRadioButtonBinario.isSelected()) {
            if (controllerClienteBin.getArquivo() == null
                    || controllerProdutoBin.getArquivo() == null
                    || controllerPedidoBin.getArquivo() == null) {

                JOptionPane.showMessageDialog(null, "Selecione os arquivos de Cliente,"
                        + " Produto e Pedido (se necessário)",
                        "Alerta", JOptionPane.WARNING_MESSAGE);

            }
            janela.controllerBin = controllerPedidoBin;
            janela.controllerClienteBin = controllerClienteBin;
            janela.controllerProdutoBin = controllerProdutoBin;

        } else {
            janela.controllerText = controllerPedidoText;
            janela.controllerClienteText = controllerClienteText;
            janela.controllerProdutoText = controllerProdutoText;

        }

        janela.setVisible(true);

    }

    public final void inicializarTexto() {
        controllerClienteText = new ControllerArquivoTextoCliente();
        controllerPedidoText = new ControllerArquivoTextoPedido();
        controllerProdutoText = new ControllerArquivoTextoProduto();
    }

    public final void inicializarBinario() {
        controllerClienteBin = new ControllerArquivoBinarioCliente();
        controllerPedidoBin = new ControllerArquivoBinarioPedido();
        controllerProdutoBin = new ControllerArquivoBinarioProduto();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarPedido;
    private javax.swing.JMenuItem jMenuItemCadastrarProduto;
    private javax.swing.JMenuItem jMenuItemGerenciarCliente;
    private javax.swing.JMenuItem jMenuItemGerenciarPedido;
    private javax.swing.JMenuItem jMenuItemGerenciarProduto;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSelecione;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonBinario;
    private javax.swing.JRadioButtonMenuItem jRadioButtonTexto;
    // End of variables declaration//GEN-END:variables
}
